### ISSUE TITLE
Toshiba Thrive tablet -can't set up device

### ISSUE THREAD

**Issue by jsjones0219** [notpod/Notpod-1.x#4]
When I go to set up new device and go to choose the music folder on the tablet, the ok button is grayed out.  Any ideas?  This was so easy on all other devices!!!  Using Win 7 on laptop and tablet is android 3.0 honeycomb.

**Comment by jaranflaath** [comment]
Hi, as stated in the help forum, this is because the tablet has to be in mass storage mode. I recommend you check out the manual or support forums or the Toshiba Thrive to see whether this is possible, and if so - how you do it. It is not an issue with Notpod, so I will close this issue. 

Should you require further assistance, please refer to the help forum. Thanks! :)
